### ISSUE TITLE
setup github action to run tests before merge

### ISSUE THREAD

**Issue by DanceParty** [awseale/discordBot#4]
We want to write a github action (there are probably examples out there) that will block any pull request from being merged _unless_ it passes our suite of tests via `npm test`

**Comment by awseale** [comment]
Added test case suite to run whenever a PR is created. Should prevent PR from being merged if it fails test suite.
Used this (https://blog.testproject.io/2021/02/01/using-github-actions-to-run-automated-tests/) as a guide
